[phases.setup]
nixPkgs = ['...']
cmds = ['...']

[phases.install]
cmds = ['gem install bundler']

[phases.build]
cmds = ['bundle install --without development production test --deployment', 'bundle exec rake assets:precompile']

[start]
cmd = './bin/rails server --environment=production'