[phases.setup]
nixPkgs = ['...']
cmds = ['...']

[phases.install]
cmds = ['gem install bundler']

[phases.build]
cmds = ['bundle install', 'bundle exec rake assets:precompile', 'RAILS_ENV=private ./bin/rake db:setup']

[start]
cmd = './bin/rails server --environment=private'