[phases.setup]
nixPkgs = ['...']
cmds = ['...', 'rbenv install 3.2.0 && rbenv global 3.2.0' ]

[phases.install]
cmds = ['gem install bundler']

[phases.build]
cmds = ['bundle install --without development production test --deployment', 'bundle exec rake assets:precompile', 'RAILS_ENV=private ./bin/rake db:setup']

[start]
cmd = './bin/rails server --environment=private'